/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutPostsRouteImport } from './routes/_layout/posts/route'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index/route'
import { Route as LayoutPostsPostIdRouteImport } from './routes/_layout/posts_/$postId/route'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutPostsRouteRoute = LayoutPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRouteRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const authLoginRouteRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRouteRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPostsPostIdRouteRoute = LayoutPostsPostIdRouteImport.update({
  id: '/posts_/$postId',
  path: '/posts/$postId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/posts': {
      id: '/_layout/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutPostsRouteImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/posts_/$postId': {
      id: '/_layout/posts_/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPostsPostIdRouteImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRouteRoute: typeof LayoutIndexRouteRoute
  LayoutDashboardRouteRoute: typeof LayoutDashboardRouteRoute
  LayoutPostsRouteRoute: typeof LayoutPostsRouteRoute
  LayoutPostsPostIdRouteRoute: typeof LayoutPostsPostIdRouteRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRouteRoute: LayoutIndexRouteRoute,
  LayoutDashboardRouteRoute: LayoutDashboardRouteRoute,
  LayoutPostsRouteRoute: LayoutPostsRouteRoute,
  LayoutPostsPostIdRouteRoute: LayoutPostsPostIdRouteRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRouteRoute
  '/login': typeof authLoginRouteRoute
  '/dashboard': typeof LayoutDashboardRouteRoute
  '/posts': typeof LayoutPostsRouteRoute
  '/posts/$postId': typeof LayoutPostsPostIdRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRouteRoute
  '/login': typeof authLoginRouteRoute
  '/dashboard': typeof LayoutDashboardRouteRoute
  '/posts': typeof LayoutPostsRouteRoute
  '/posts/$postId': typeof LayoutPostsPostIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRouteRoute
  '/(auth)/login': typeof authLoginRouteRoute
  '/_layout/dashboard': typeof LayoutDashboardRouteRoute
  '/_layout/posts': typeof LayoutPostsRouteRoute
  '/_layout/posts_/$postId': typeof LayoutPostsPostIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/login' | '/dashboard' | '/posts' | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/posts' | '/posts/$postId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/(auth)/login'
    | '/_layout/dashboard'
    | '/_layout/posts'
    | '/_layout/posts_/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  authLoginRouteRoute: typeof authLoginRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  authLoginRouteRoute: authLoginRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/(auth)/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/dashboard",
        "/_layout/posts",
        "/_layout/posts_/$postId"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index/route.tsx",
      "parent": "/_layout"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login/route.tsx"
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard/route.tsx",
      "parent": "/_layout"
    },
    "/_layout/posts": {
      "filePath": "_layout/posts/route.tsx",
      "parent": "/_layout"
    },
    "/_layout/posts_/$postId": {
      "filePath": "_layout/posts_/$postId/route.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
