/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const appLayoutLazyImport = createFileRoute('/(app)/_layout')()
const authLoginIndexLazyImport = createFileRoute('/(auth)/login/')()
const appLayoutIndexLazyImport = createFileRoute('/(app)/_layout/')()
const appLayoutPostsIndexLazyImport = createFileRoute('/(app)/_layout/posts/')()
const appLayoutDashboardIndexLazyImport = createFileRoute(
  '/(app)/_layout/dashboard/',
)()
const appLayoutPostsPostIdIndexLazyImport = createFileRoute(
  '/(app)/_layout/posts/$postId/',
)()

// Create/Update Routes

const appLayoutLazyRoute = appLayoutLazyImport
  .update({
    id: '/(app)/_layout',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/_layout.lazy').then((d) => d.Route))

const authLoginIndexLazyRoute = authLoginIndexLazyImport
  .update({
    id: '/(auth)/login/',
    path: '/login/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/login/index.lazy').then((d) => d.Route))

const appLayoutIndexLazyRoute = appLayoutIndexLazyImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutLazyRoute,
  } as any)
  .lazy(() => import('./routes/(app)/_layout/index.lazy').then((d) => d.Route))

const appLayoutPostsIndexLazyRoute = appLayoutPostsIndexLazyImport
  .update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => appLayoutLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_layout/posts/index.lazy').then((d) => d.Route),
  )

const appLayoutDashboardIndexLazyRoute = appLayoutDashboardIndexLazyImport
  .update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => appLayoutLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_layout/dashboard/index.lazy').then((d) => d.Route),
  )

const appLayoutPostsPostIdIndexLazyRoute = appLayoutPostsPostIdIndexLazyImport
  .update({
    id: '/posts/$postId/',
    path: '/posts/$postId/',
    getParentRoute: () => appLayoutLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/_layout/posts/$postId/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutLazyImport
      parentRoute: typeof undefinedRoute
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexLazyImport
      parentRoute: typeof appLayoutLazyImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_layout/dashboard/': {
      id: '/(app)/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appLayoutDashboardIndexLazyImport
      parentRoute: typeof appLayoutLazyImport
    }
    '/(app)/_layout/posts/': {
      id: '/(app)/_layout/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof appLayoutPostsIndexLazyImport
      parentRoute: typeof appLayoutLazyImport
    }
    '/(app)/_layout/posts/$postId/': {
      id: '/(app)/_layout/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof appLayoutPostsPostIdIndexLazyImport
      parentRoute: typeof appLayoutLazyImport
    }
  }
}

// Create and export the route tree

interface appLayoutLazyRouteChildren {
  appLayoutIndexLazyRoute: typeof appLayoutIndexLazyRoute
  appLayoutDashboardIndexLazyRoute: typeof appLayoutDashboardIndexLazyRoute
  appLayoutPostsIndexLazyRoute: typeof appLayoutPostsIndexLazyRoute
  appLayoutPostsPostIdIndexLazyRoute: typeof appLayoutPostsPostIdIndexLazyRoute
}

const appLayoutLazyRouteChildren: appLayoutLazyRouteChildren = {
  appLayoutIndexLazyRoute: appLayoutIndexLazyRoute,
  appLayoutDashboardIndexLazyRoute: appLayoutDashboardIndexLazyRoute,
  appLayoutPostsIndexLazyRoute: appLayoutPostsIndexLazyRoute,
  appLayoutPostsPostIdIndexLazyRoute: appLayoutPostsPostIdIndexLazyRoute,
}

const appLayoutLazyRouteWithChildren = appLayoutLazyRoute._addFileChildren(
  appLayoutLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appLayoutIndexLazyRoute
  '/login': typeof authLoginIndexLazyRoute
  '/dashboard': typeof appLayoutDashboardIndexLazyRoute
  '/posts': typeof appLayoutPostsIndexLazyRoute
  '/posts/$postId': typeof appLayoutPostsPostIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof appLayoutIndexLazyRoute
  '/login': typeof authLoginIndexLazyRoute
  '/dashboard': typeof appLayoutDashboardIndexLazyRoute
  '/posts': typeof appLayoutPostsIndexLazyRoute
  '/posts/$postId': typeof appLayoutPostsPostIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)/_layout': typeof appLayoutLazyRouteWithChildren
  '/(app)/_layout/': typeof appLayoutIndexLazyRoute
  '/(auth)/login/': typeof authLoginIndexLazyRoute
  '/(app)/_layout/dashboard/': typeof appLayoutDashboardIndexLazyRoute
  '/(app)/_layout/posts/': typeof appLayoutPostsIndexLazyRoute
  '/(app)/_layout/posts/$postId/': typeof appLayoutPostsPostIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/posts' | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/posts' | '/posts/$postId'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/(app)/_layout/'
    | '/(auth)/login/'
    | '/(app)/_layout/dashboard/'
    | '/(app)/_layout/posts/'
    | '/(app)/_layout/posts/$postId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appLayoutLazyRoute: typeof appLayoutLazyRouteWithChildren
  authLoginIndexLazyRoute: typeof authLoginIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  appLayoutLazyRoute: appLayoutLazyRouteWithChildren,
  authLoginIndexLazyRoute: authLoginIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)/_layout",
        "/(auth)/login/"
      ]
    },
    "/(app)/_layout": {
      "filePath": "(app)/_layout.lazy.tsx",
      "children": [
        "/(app)/_layout/",
        "/(app)/_layout/dashboard/",
        "/(app)/_layout/posts/",
        "/(app)/_layout/posts/$postId/"
      ]
    },
    "/(app)/_layout/": {
      "filePath": "(app)/_layout/index.lazy.tsx",
      "parent": "/(app)/_layout"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.lazy.tsx"
    },
    "/(app)/_layout/dashboard/": {
      "filePath": "(app)/_layout/dashboard/index.lazy.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/posts/": {
      "filePath": "(app)/_layout/posts/index.lazy.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/posts/$postId/": {
      "filePath": "(app)/_layout/posts/$postId/index.lazy.tsx",
      "parent": "/(app)/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
